[project]
dependencies = [
    "appwindows >= 1.3.0",
    "PyAutoGui >= 0.9.0",
    "numpy >= 1.20",
    "pillow >= 11.0",
    "screeninfo >= 0.8",
    "thefuzz >= 0.20.0"
]
name = "apparser"
version = "1.1.0"
authors = [
    { name = "Terochkin A.S", email = "apparser.development@gmail.com" },
]
description = "Apparser is a Python library designed for automating desktop applications and managing UI interfaces using artificial intelligence, such as OCR or object detection models. "
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Operating System :: Microsoft :: Windows :: Windows 11",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
    "Environment :: X11 Applications",
    "Environment :: Win32 (MS Windows)",
    "Environment :: MacOS X :: Aqua",
]
keywords = [
    "automation",
    "desktop-automation",
    "gui-automation",
    "ui-automation",
    "computer-vision",
    "object-detection",
    "ocr",
    "ui",
    "cv",
    "yolo",
    "text-recognition",
    "screen-recognition",
    "window-management",
    "mouse-automation",
    "keyboard-automation",
    "speech-synthesis",
    "tts",
    "app-control"
]
[project.urls]
Docs = "https://apparser-development.github.io/apparser/"
Repository = "https://github.com/apparser-development/apparser"
Issues = "https://github.com/apparser-development/apparser/issues"

[project.optional-dependencies]
cv = [
    "ultralytics >= 8.4.30"
]

ocr = [
    "easyocr >= 1.7.2, < 2.0",
    "paddleocr >= 3.5.0",
    "paddlepaddle >= 3.3.1"
]

speak = [
    "ChatTTS",
    "sounddevice",
    "torch"
]

all = [
  "apparser[cv]",
  "apparser[ocr]",
  "apparser[speak]",
]
