[project]
dependencies = ["appwindows >= 1.2.0",
            "numpy>=2.0",
            "pillow~=11.1.0",
            "mouse >= 0.7.1",
            "keyboard >= 0.13.2",
            "easyocr~=1.7.2",
            "thefuzz~=0.22.1"]
name = "apparser"
version = "1.0.0"
authors = [
 {name="Terochkin A.S", email="apparser.development@gmail.com" },
]
description = "The apparser library is designed for testing and managing computer programs."
readme = "README.md"
requires-python = ">=3.12.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Operating System :: Microsoft :: Windows :: Windows 11",
    "Operating System :: POSIX :: Linux",
    "Environment :: X11 Applications",
    "Environment :: Win32 (MS Windows)"
]

[project.urls]
Repository = "https://github.com/lexter0705/apparser"
Issues = "https://github.com/lexter0705/apparser/issues"
